spring:
  application:
    name: janak-spring-cloud-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/janakgithub/environment-variable-repo.git
          username: janakgithub
          password: ******

server:
  port: ${port:8888}

